name: growth_lab
version: "0.1.0"
profile: growth_lab

model-paths: ["models"]
macro-paths: ["macros"]
target-path: target
clean-targets: [target, dbt_packages]

models:
  growth_lab:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
